### PR TITLE
Transform daily survey

### PR DESCRIPTION
**Pull request by jordan2lee**
update schema for input of questions from k2o daily survey

### CODE REVIEW

**Comment by kellrott** [comment]
All of the changes in spaces make it pretty hard to review the actual changes.

**Comment by jordan2lee** [comment]
> All of the changes in spaces make it pretty hard to review the actual changes.

I didn't actively change spaces, likely my text editor added these spaces. I'll look into it for next PR.

**Comment by jordan2lee** [comment]
all daily survey responses have been added. exception is `QID8_34` that appears to be a bug in central db - mappings don't match. have included `QID8_34_TEXT` in this PR. Will need to cycle back to add in `QID8_34` at a later time

**Comment by jordan2lee** [comment]
cost of COVID survey responses added to schema

**Comment by kellrott** [comment]
I don't see any non whitespace changes in `gdcdictionary/schemas/diagnosis.yaml`. Can you checkout the copy from origin/master to minimize the differences?

**Pull request merged**
